server:
    port: 30030
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: article-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
  application:
    name: article-service
  datasource:
    url: jdbc:postgresql://localhost:5432/article
    username: root
    driver-class-name: org.postgresql.Driver
    password: 8834
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
