server:
  port: 30032
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: comment--service
  datasource:
    url: jdbc:postgresql://localhost:5433/comment
    username: root
    driver-class-name: org.postgresql.Driver
    password: 8834
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration